
CREATE TABLE "CLOSET" (
    "ID" BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "OWNER" VARCHAR(255) NOT NULL,
    "NAME" VARCHAR(255) NOT NULL
);

CREATE TABLE "ITEM" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "TYPE" VARCHAR(255) NOT NULL,
    "DATE" DATE,
    "GENDER" VARCHAR(10) NOT NULL CHECK ("GENDER" IN ('MALE', 'FEMALE', 'BOTH')),
    "SIZE" VARCHAR(20),
    "NOTE" VARCHAR(255),
    "CLOSET" BIGINT REFERENCES CLOSET (ID),
);


