
CREATE TABLE "CLOSET" (
    "ID" BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "OWNER" VARCHAR(255) NOT NULL,
    "NAME" VARCHAR(255) NOT NULL
);



CREATE TABLE "ITEM" (
    "ID" BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "TYPE" VARCHAR(255) NOT NULL,
    "ADD_DATE" DATE,
    "GENDER" VARCHAR(10) NOT NULL CHECK ("GENDER" IN ('MALE', 'FEMALE', 'BOTH')),
    "SIZE" VARCHAR(20),
    "NOTE" VARCHAR(255),
    "CLOSETID" BIGINT REFERENCES CLOSET (ID)
);



